name: Build
on:
  workflow_dispatch:
    inputs:
      architecture:
        description: "Target CPU architecture"
        required: true
        default: x64
        type: choice
        options:
          - x64
          - arm64
      release_type:
        description: "WSA release type"
        required: true
        default: retail
        type: choice
        options:
          - Retail
          - Release Preview
          - Insider Slow
          - Insider Fast
      magisk_version:
        description: "Magisk channel"
        required: true
        default: stable
        type: choice
        options:
          - stable
          - beta
          - canary
          - debug
          - release
      install_gapps:
        description: "Install GApps"
        required: true
        default: true
        type: boolean
      remove_amazon:
        description: "Remove Amazon Store"
        required: true
        default: false
        type: boolean
      root_solution:
        description: "Root solution"
        required: true
        default: magisk
        type: choice
        options:
          - magisk
          - kernelsu
          - none
  workflow_call:
    inputs:
      architecture:
        required: false
        default: x64
        type: string
      release_type:
        required: false
        default: insider fast
        type: string
      magisk_version:
        required: false
        default: stable
        type: string
      install_gapps:
        required: false
        default: true
        type: boolean
      remove_amazon:
        required: false
        default: false
        type: boolean
      root_solution:
        required: false
        default: magisk
        type: string
      reverse-ssh:
        required: false
        default: false
        type: string
      reverse-ssh-public-key:
        required: false
        type: string
      reverse-ssh-remote-address-port:
        required: false
        type: string
env:
  REVERSE_SSH: ${{ inputs.reverse-ssh }}
  REVERSE_SSH_PUBLIC_KEY: ${{ inputs.reverse-ssh-public-key }}
  REVERSE_SSH_REMOTE_ADDRESS_PORT: ${{ inputs.reverse-ssh-remote-address-port }}
  WSA_BUILD_ARCHITECTURE: ${{ inputs.architecture }}
  WSA_BUILD_RELEASE_TYPE: ${{ inputs.release_type }}
  WSA_BUILD_MAGISK_VERSION: ${{ inputs.magisk_version }}
  WSA_BUILD_INSTALL_GAPPS: ${{ inputs.install_gapps }}
  WSA_BUILD_REMOVE_AMAZON: ${{ inputs.remove_amazon }}
  WSA_BUILD_ROOT_SOLUTION: ${{ inputs.root_solution }}
jobs:
  build-magisk-on-wsa:
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Open reverse SSH if in test mode
        run: ./github_actions_reverse_ssh.sh
      - name: Installing dependencies for building Magisk on WSA
        run: ./install_dependencies.sh
      - name: Building Magisk on WSA
        run: ./build_wsa.sh
      - name: Archiving and compressing artifact
        run: |
          cd MagiskOnWSALocal/output
          tar -cvf ../MagiskOnWSA.tar .
          cd ../..
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MagiskOnWSA.tar
          path: MagiskOnWSALocal/MagiskOnWSA.tar
  build-wsa-patch:
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Updating package manager cache
        run: sudo apt update -y
      - name: Installing dependencies
        run: sudo apt install p7zip
      - name: Downloading and extracing WSAPatch release files
        run: |
          cd WSAPatch
          bash -e -x download.sh file_list.csv
          7z e release.7z
          cd ..
      - name: Archiving and compressing artifact
        run: |
          cd WSAPatch
          tar -cvf ../WSAPatch.tar *.dll
          cd ..
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: WSAPatch.tar
          path: WSAPatch.tar
  build-magisk-on-wsa-10:
    needs:
      - build-wsa-patch
      - build-magisk-on-wsa
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/
      - name: Extracing files
        run: |
          cd artifacts

          for name in *
          do
              mv $name/$name ../$name
              rmdir $name
              mv ../$name ./
          done

          tar -xvf WSAPatch.tar
          rm WSAPatch.tar
          tar -xvf MagiskOnWSA.tar
          rm MagiskOnWSA.tar

          cd ..
      - name: Applying patch for Windows 10
        run: |
          cd artifacts
          mv *.dll */WsaClient/
          patch --binary */AppxManifest.xml ../wsa_windows_10.patch
          cd ..
      - name: Archiving and compressing artifact
        run: |
          cd artifacts
          tar -cvf ../MagiskOnWSA10.tar .
          cd ..
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MagiskOnWSA10.tar
          path: MagiskOnWSA10.tar
